### ISSUE TITLE
custom icon like instagram

### ISSUE THREAD

**Issue by vjerryv** [googlemaps/google-maps-ios-utils#42]
how can I do like this?
Any example? 
thanks

![utility-markercluster-custom](https://cloud.githubusercontent.com/assets/3232807/18644031/543958c4-7eda-11e6-83e9-738cf2f74c9c.png)

**Comment by mountainvat** [comment]
We have released a new version 1.1.x with easy marker customization. Please update your cocoapod or source files.
For more details see https://github.com/googlemaps/google-maps-ios-utils/blob/master/CustomMarkers.md

**Comment by ajPT** [comment]
@mountainvat thanks for the work to create an easy way to customize the markers but I still have a question.
How can we change the image using the "marker.icon" right? But how can we maintain/add the number of items in the cluster?

**Comment by mountainvat** [comment]
Please take a look at https://github.com/googlemaps/google-maps-ios-utils/blob/master/app/CustomMarkerViewController.m for how to implement the ```- (void)renderer:(id<GMUClusterRenderer>)renderer willRenderMarker:(GMSMarker *)marker``` method.

What do you mean by maintain/add the number of items in the cluster?

**Comment by ajPT** [comment]
@mountainvat to show the number of items in the cluster in front of the image.
e.g: "5" (representing the number of items in that cluster).

**Comment by mountainvat** [comment]
You would have to use UIGraphics to draw the number on top of the mashed up image. See https://github.com/googlemaps/google-maps-ios-utils/blob/master/src/Clustering/View/GMUDefaultClusterIconGenerator.m for how the number is drawn.
